global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: control-communication
    metrics_path: /metrics
    static_configs:
      - targets: ["control-communication:5000"]

  - job_name: metrics-aggregator
    metrics_path: /metrics
    static_configs:
      - targets: ["metrics-aggregator:7000"]
